### ISSUE TITLE
Installation and non-compatible packet issue

### ISSUE THREAD

**Issue by ssditt** [fl4p/influxdb-udp-relay#2]
Home Assistant Core 2023.9.2 (std VirtualBox image) + InfluxDb Add-on 4.7.0
Installing this influxdb-udp-relay Add-on it does not connect to InfluxDb. Added manually as external server and working.
This Add-on works for regular UDP packets, but when a non-standard packet comes, it crashes on utf-8 error and program doesn't restart (watch dog enabled). I would guess that an exception handling is missing. It should be great to have this exception handled and log an info about wrong packet (l haven't log file now as it happens rarely, but happens).
btw - is this Add-on a must or is there any InfluxDb Add-on supporting InfluxDb UDP line protocol directly?

**Comment by fl4p** [comment]
I've pushed an update which adds exception handling.

the influxdb add-on (https://github.com/hassio-addons/addon-influxdb/) doesn't support UDP writes out-of-the box because it would require to run the add-on on the host network (set `host_network: true`). It needs a couple of simple changes, but the maintainer refuses and I couldn't find a reason (https://github.com/hassio-addons/addon-influxdb/issues/270)

When I have time I'll create a fork of the add-on with UDP support

**Comment by ssditt** [comment]
Thanks for your prompt response!
I have successfuly upgraded the Add-on! I will let you know the result after some time (or not if will forget about it as there won't be any problem anymore :-) )
And thanks for your effort to get the functionality to InfluxDb Add-on directly!
